repos:
- repo: local
  hooks:
    - id: cargo-fmt-server
      name: Format Rust server
      entry: bash -c 'cd ./server && cargo fmt -- --check'
      language: system
      types: [rust]
      pass_filenames: false

    - id: cargo-build-server
      name: Build Rust server
      entry: bash -c 'cd ./server && cargo check'
      language: system
      types: [rust]
      pass_filenames: false